from pathlib import Path

import pytest

from lazytest.cmake_build import build_command
from lazytest.config import AppConfig, load_config, parse_config
from lazytest.ctest_discovery import discovery_command
from lazytest.models import DiscoveredTest, ProcessResult
from lazytest.test_runner import ctest_command_for_names, run_tests


def test_build_command_uses_cmake_build_and_parallel(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr("lazytest.cmake_build.os.cpu_count", lambda: 8)

    command = build_command(AppConfig(build_dir=Path("/tmp/build")), "unit_tests")

    assert command == [
        "cmake",
        "--build",
        "/tmp/build",
        "--target",
        "unit_tests",
        "--parallel",
        "8",
    ]


def test_build_command_supports_build_preset(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr("lazytest.cmake_build.os.cpu_count", lambda: 4)

    command = build_command(AppConfig(build_preset="debug"), "unit_tests")

    assert command[:5] == ["cmake", "--build", "--preset", "debug", "--target"]


def test_ctest_command_prefers_tests_from_file() -> None:
    command = ctest_command_for_names(
        AppConfig(build_dir=Path("/tmp/build")),
        ["unit.math"],
        tests_from_file=Path("/tmp/names.txt"),
    )

    assert command == [
        "ctest",
        "--test-dir",
        "/tmp/build",
        "--tests-from-file",
        "/tmp/names.txt",
        "--output-on-failure",
    ]


def test_ctest_command_has_anchored_regex_fallback() -> None:
    command = ctest_command_for_names(AppConfig(build_dir=Path("/tmp/build")), ["a+b"])

    assert command == [
        "ctest",
        "--test-dir",
        "/tmp/build",
        "-R",
        "^a\\+b$",
        "--output-on-failure",
    ]


def test_discovery_command_uses_json_show_only() -> None:
    assert discovery_command(AppConfig(build_dir=Path("build"))) == [
        "ctest",
        "--show-only=json-v1",
        "--test-dir",
        "build",
    ]


def test_parse_config_validates_and_loads_fields() -> None:
    config = parse_config(
        {
            "build_dir": "out",
            "test_preset": "test-debug",
            "build_preset": "debug",
            "default_build_target": "all_tests",
            "extra_ctest_args": ["--verbose"],
            "extra_build_args": ["--config", "Debug"],
            "target_mappings": [{"pattern": "^unit", "target": "unit_tests"}],
        }
    )

    assert config.build_dir == Path("out")
    assert config.test_preset == "test-debug"
    assert config.target_mappings[0].target == "unit_tests"


def test_parse_config_allows_omitted_optional_list_fields() -> None:
    config = parse_config({"build_dir": "build"})

    assert config.extra_ctest_args == ()
    assert config.extra_build_args == ()


def test_parse_config_rejects_bad_regex() -> None:
    with pytest.raises(ValueError, match="Invalid target mapping regex"):
        parse_config({"target_mappings": [{"pattern": "[", "target": "x"}]})


def test_load_config_defaults_to_current_dir_inside_ctest_build_dir(tmp_path: Path) -> None:
    (tmp_path / "CTestTestfile.cmake").write_text("# generated by cmake\n", encoding="utf-8")

    config = load_config(tmp_path)

    assert config.build_dir == tmp_path.resolve()


def test_load_config_still_defaults_to_build_outside_ctest_build_dir(tmp_path: Path) -> None:
    config = load_config(tmp_path)

    assert config.build_dir == (tmp_path / "build").resolve()


@pytest.mark.asyncio
async def test_run_tests_falls_back_when_tests_from_file_is_unavailable(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    commands: list[list[str]] = []

    async def fake_support() -> bool:
        return False

    async def fake_run_streaming(command, *, cwd, on_output):
        commands.append(command)
        return ProcessResult(command=tuple(command), returncode=0)

    monkeypatch.setattr("lazytest.test_runner.ctest_supports_tests_from_file", fake_support)
    monkeypatch.setattr("lazytest.test_runner.run_streaming", fake_run_streaming)
    output: list[str] = []

    result = await run_tests(
        AppConfig(build_dir=Path("/tmp/build")),
        [DiscoveredTest(name="unit.math")],
        output.append,
    )

    assert result.ok
    assert commands == [
        ["ctest", "--test-dir", "/tmp/build", "-R", "^unit\\.math$", "--output-on-failure"]
    ]
    assert "anchored regex fallback" in "".join(output)
